repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.5.3

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "3.2.1"
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: |
          (?x)^(
              .*ro-crate-metadata.json$|
              modules/nf-core/.*|
              subworkflows/nf-core/.*|
              .*\.snap$
          )$
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
              .*ro-crate-metadata.json$|
              modules/nf-core/.*|
              subworkflows/nf-core/.*|
              .*\.snap$
          )$
