name: "multifasta_to_singlefasta"
description: Convert a multi-FASTA file into a single-sequence FASTA file.
tools: []
input:
  - - meta:
        type: map
        description: Groovy Map containing sample information.
    - fasta:
        type: file
        description: Multi-FASTA input.
        pattern: "*.{fa,fasta}"
output:
  input_fasta:
    - - meta:
          type: map
          description: Groovy Map containing sample information.
      - "${meta.id}.fasta":
          type: file
          description: Single-sequence FASTA file.
          pattern: "*.fasta"
  versions_sed:
    - - "${task.process}":
          type: string
          description: The process the versions were collected from.
      - sed:
          type: string
          description: The tool name.
      - 'sed --version 2>&1 | sed "s/^.*GNU sed) //; s/ .*$//"':
          type: eval
          description: The expression to obtain the version of the tool.
topics:
  versions:
    - - "${task.process}":
          type: string
          description: The process the versions were collected from.
      - sed:
          type: string
          description: The tool name.
      - 'sed --version 2>&1 | sed "s/^.*GNU sed) //; s/ .*$//"':
          type: eval
          description: The expression to obtain the version of the tool.
