name: assemble_modelcif
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::biopython=1.84
  - conda-forge::pyyaml=6.0.2
  - conda-forge::pip=24.2
  - pip:
    - modelcif>=1.7
    - msgpack>=1.0
