FROM nvidia/cuda:11.1.1-cudnn8-runtime-ubuntu18.04
LABEL authors="Luisa Santus, Athanasios Baltzis" \
    title="nf-friendly AF2 MSA docker image" \
    Version="v0.1" \
    description="Docker image containing all software requirements to run AF2_MSA using the nf-core/proteinfold pipeline"


# Use bash to support string substitution.
SHELL ["/bin/bash", "-c"]

# Add env variables
ENV LD_LIBRARY_PATH="/conda/lib:/usr/local/cuda-11.1/lib64:$LD_LIBRARY_PATH"
ENV PATH="/conda/bin:$PATH"

RUN rm /etc/apt/sources.list.d/cuda.list && \
    rm /etc/apt/sources.list.d/nvidia-ml.list && \
    apt-key del 7fa2af80 && \
    apt-get update && apt-get install -y --no-install-recommends wget && \
    wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-keyring_1.0-1_all.deb && \
    dpkg -i cuda-keyring_1.0-1_all.deb
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
        build-essential \
        cmake \
        cuda-command-line-tools-11-1 \
        git \
        hmmer \
        kalign \
        tzdata \
        wget \
        vim \
        && rm -rf /var/lib/apt/lists/*

# Clone AF2 git checkout d3327d968c6cfa31da53324c173ff635ed1ec0b6 && \
RUN git clone https://github.com/luisas/alphafold_split.git /app/alphafold && \
    cd /app/alphafold && \
    git checkout 095768b24e9ee76a3f0f85c706f2f91cbfca659f && \
    cd -

# Compile HHsuite from source
RUN git clone --branch v3.3.0 https://github.com/soedinglab/hh-suite.git /tmp/hh-suite \
    && mkdir /tmp/hh-suite/build \
    &&	cd /tmp/hh-suite/build \
    &&	cmake -DCMAKE_INSTALL_PREFIX=/opt/hhsuite -DHAVE_AVX2=1 .. \
    && make -j 4 && make install \
    && ln -s /opt/hhsuite/bin/* /usr/bin \
    && cd - && rm -rf /tmp/hh-suite

# Install Miniconda package manager
RUN wget -q -P /tmp \
        https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
            && bash /tmp/Miniconda3-latest-Linux-x86_64.sh -b -p /conda \
            && rm /tmp/Miniconda3-latest-Linux-x86_64.sh

# Install conda packages
RUN /conda/bin/conda update -qy conda \
        && /conda/bin/conda install -y -c conda-forge \
            pip \
            python=3.9

# Install pip packages
RUN /conda/bin/pip3 install --upgrade pip \
    && /conda/bin/pip3 install -r /app/alphafold/requirements_msa.txt
