FROM debian:11
LABEL authors="Athanasios Baltzis" \
    title="nf-friendly debian 11 docker image" \
    Version="v0.1" \
    description="Docker image containing all software requirements to download the databases and parameteres for AF2 and Colabfold"

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
	wget \
	aria2 \
	procps \
	tar \
	rsync \
	&& rm -rf /var/lib/apt/lists/*
