FROM nvidia/cuda:12.6.0-cudnn-devel-ubuntu24.04

LABEL Author="Patricia Bota" \
      title="nfcore/proteinfold_rosettafold2na" \
      Version="0.9.0" \
      description="Docker image containing all software requirements to run the RF2NA module using the nf-core/proteinfold pipeline"

# Set up environment variables: add the RF2NA repository to PYTHONPATH and adjust PATH
ENV PYTHONPATH="/app/RoseTTAFold2NA" \
    PATH="/conda/bin:/app/RoseTTAFold2NA:$PATH" \
    DGLBACKEND="pytorch" \
    LD_LIBRARY_PATH="/conda/lib:/usr/local/cuda-12.6/lib64:$LD_LIBRARY_PATH"

# Install system dependencies and Miniforge
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y wget git && \
    wget -q -P /tmp "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh" && \
    bash /tmp/Miniforge3-$(uname)-$(uname -m).sh -b -p /conda && \
    rm -rf /tmp/Miniforge3-$(uname)-$(uname -m).sh /var/lib/apt/lists/* && \
    apt-get autoremove -y && apt-get clean -y

# Clone the RF2NA repository, create the conda environment, and install SE(3)-Transformer
RUN git clone --single-branch --depth 1 https://github.com/uw-ipd/RoseTTAFold2NA.git /app/RoseTTAFold2NA && \
    cd /app/RoseTTAFold2NA && \
    /conda/bin/mamba env create --file=RF2na-linux.yml && \
    /conda/bin/mamba run -n RF2NA bash -c "cd /app/RoseTTAFold2NA/SE3Transformer && \
      pip install --no-cache-dir -r requirements.txt && \
      python setup.py install" && \
    /conda/bin/mamba clean --all --force-pkgs-dirs -y

# Download pre-trained weights for RF2NA into the network folder
RUN cd /app/RoseTTAFold2NA/network && \
    wget https://files.ipd.uw.edu/dimaio/RF2NA_apr23.tgz && \
    tar xvfz RF2NA_apr23.tgz && \
    rm -f RF2NA_apr23.tgz && \
    apt-get autoremove -y && apt-get remove --purge -y wget git && apt-get clean -y
