FROM python:3.9-slim

LABEL authors="Nathan Glades <n.glades@unsw.edu.au>" \
	title="Australian-Structural-Biology-Computing/create-samplesheet" \
	Version="1.0" \
	description="Dockerfile containing samplesheetutils"

RUN apt-get update && \
	apt-get install -y --no-install-recommends \
	build-essential 

RUN pip install samplesheetutils

