name: ASBC branch protection

on:
  pull_request:
    branches:
      - main
      - master

permissions: {}

jobs:
  enforce-dev-source:
    name: enforce-dev-source
    runs-on: ubuntu-latest
    steps:
      - name: Check PR source branch
        env:
          HEAD_REPO: ${{ github.event.pull_request.head.repo.full_name }}
        run: |
          [[ "$HEAD_REPO" == "Australian-Structural-Biology-Computing/proteinfold" ]] && [[ "$GITHUB_HEAD_REF" == "dev" ]]
