name: Run scientific validation nf-test
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NFT_VER: "0.9.4"
  NFT_WORKDIR: "~"
  NXF_ANSI_LOG: false
  NXF_SINGULARITY_CACHEDIR: ${{ github.workspace }}/.singularity
  NXF_SINGULARITY_LIBRARYDIR: ${{ github.workspace }}/.singularity

jobs:
  get-shards:
    name: Get scientific validation shards
    runs-on:
      - runs-on=${{ github.run_id }}-scientific-validation-shards
      - runner=4cpu-linux-x64
    outputs:
      shard: ${{ steps.set-shards.outputs.shard }}
      total_shards: ${{ steps.set-shards.outputs.total_shards }}
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Get shards
        id: set-shards
        uses: ./.github/actions/get-shards
        env:
          NFT_VER: ${{ env.NFT_VER }}
        with:
          tags: "scientific"
          max_shards: 8

  nf-test-scientific:
    needs: [get-shards]
    if: ${{ needs.get-shards.outputs.total_shards != '0' }}
    runs-on:
      - runs-on=${{ github.run_id }}-scientific-validation
      - runner=4cpu-linux-x64
    name: "Scientific validation | docker | ${{ matrix.shard }}/${{ needs.get-shards.outputs.total_shards }}"
    strategy:
      fail-fast: false
      matrix:
        shard: ${{ fromJson(needs.get-shards.outputs.shard) }}
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.14"

      - name: Install BioPython requirements
        run: pip install -r tests/requirements.txt

      - name: Run nf-test Action
        uses: ./.github/actions/nf-test
        env:
          NFT_WORKDIR: ${{ env.NFT_WORKDIR }}
          NXF_VERSION: "25.10.4"
        with:
          profile: docker
          shard: ${{ matrix.shard }}
          total_shards: ${{ needs.get-shards.outputs.total_shards }}
          tags: "scientific"

  confirm-pass:
    needs: [nf-test-scientific]
    if: always()
    runs-on:
      - runs-on=${{ github.run_id }}-confirm-pass
      - runner=2cpu-linux-x64
    steps:
      - name: One or more tests failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

      - name: One or more tests cancelled
        if: ${{ contains(needs.*.result, 'cancelled') }}
        run: exit 1

      - name: All tests ok
        if: ${{ contains(needs.*.result, 'success') }}
        run: exit 0
